### ISSUE TITLE
Variables in the snippet's string

### ISSUE THREAD

**Issue by AndreaGennaioli** [NotReallyEight/atn-modmail#6]
Make it possible to add a variable in the snippet string in snippets.js so that we can interact with the id, mention and tag of the user who opened the ticket inside it.

Something like that:
```js
module.exports = { 
    partner: "Hey {{userTag}}, here are the requirements for the partnership: ..."
}
```

**Comment by NotReallyEight** [comment]
Will look into it later 👍

**Comment by RealPyotr** [comment]
eight eight eight eight

**Comment by NotReallyEight** [comment]
Please do not comment any random things in an Issue/Pull Request. Thank you.

**Comment by RealPyotr** [comment]
sorry

**Comment by NotReallyEight** [comment]
Finished
