### ISSUE TITLE
Not an issue, but a suggestion

### ISSUE THREAD

**Issue by VineyS** [NotReallyEight/atn-modmail#8]
It would be nice if the modmail could make transcripts on the ticket. This would help the moderator of a server to review any ticket message made up with the user.

**Comment by NotReallyEight** [comment]
Will take it in consideration in a future release of the bot once the host gets back up. Thanks for the suggestion though!

**Comment by RealPyotr** [comment]
NOT AN ISSUE BUT SUGGESTION DASHBOARD AND CREATE PERSONAL COMMANDS

**Comment by NotReallyEight** [comment]
This is a modmail bot, please do not write in caps and write stuff in topic or I will mute you from comment to any issue/pull request in this repository.

**Comment by VineyS** [comment]
It would be nice if there was localhost log viewer allowing user to view transcripts and a snippet webconfiguration allowing users to make changes to existing snippets or add new ones with ease.

**Comment by NotReallyEight** [comment]
About the log viewer I will need to actually learn a little bit more of HTML and CSS as I really suck at that, maybe a log channel could be a good idea for it at the moment.
About the web configuration same as above so it will only be a command thingy for it.

**Comment by NotReallyEight** [comment]
Working on this one, transcripts will be available over a Sourcebin link as I can not make a web server completely for the bot and it will be too heavy for users.
